editor: 0
theme: 3
showNewVersionIcon: false
hideAfterStartup: true
randomControllerPort: false
bypassText: |
  bypass:
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
mixinText: |-
  mixin: # object
    hosts:
      '*.clash.dev': 127.0.0.1
      '.dev': 127.0.0.1
      'alpha.clash.dev': '::1'
connProxy: 1
connProfile: true
connMode: true
childProcessText: |
  processes: # array
    # 启动订阅转换程序，端口号25500
    - command: subconverter.exe
      options:
        cwd: subconverter # 子进程工作目录
        windowsHide: true # 隐藏子进程的控制台窗口
        
    # 启动解锁网易云灰色歌曲程序，端口号8080
    - command: unblockneteasemusic.exe
      args:
        - "-o"
        - "kuwo"
        - "kugou"
        - "bilibili"
      options:
        cwd: unblockneteasemusic
        windowsHide: true 

    # 清除dns解析缓存
    - command: ipconfigFlushdns.bat
      options:
        cwd: ipconfigFlushdns
        windowsHide: true 
      log: true

    # 解决 ChineseMainland Github DNS 污染
    - command: fastgithubStart.bat
      options:
        cwd: fastgithub
        windowsHide: true
connKeepOld: true
shortcutMixin: ""
showProxyFilter: false
fontFamily: 楷体
systemProxyTypeIndex: 0
pacContentText: >-
  function FindProxyForURL(url, host) {
    return "PROXY 127.0.0.1:%mixed-port%; SOCKS5 127.0.0.1:%mixed-port%; DIRECT;"
  }
profileParsersText: |
  parsers: # array
selectAfterUpdated: false
proxyItemWidth: ""
connShowType: 0
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
editProfileWithCFWEditor: true
mixinType: 0
proxyDelayType: 0
connChainType: 2
trayProxiesStyle: 1
useSystemEmoji: false
useModeIcons: false
latencyTimeout: 3000
