---
#-------------------------------------------------------------#
# Clash使用手册 https://dreamacro.github.io/clash/zh_CN
# Clash管理面板 https://clash.razord.top https://yacd.haishan.me
#-------------------------------------------------------------#
# HTTP(S) 和 SOCKS4(A)/SOCKS5 代理服务共用一个端口
mixed-port: 7890

# Linux 和 macOS 的透明代理服务端口 (TCP 和 TProxy UDP 重定向)
redir-port: 7892

# 允许局域网的连接 (需系统防火墙放行)
allow-lan: false

# 仅在将allow-lan设置为true时适用
# "*": 绑定所有IP地址
# 192.168.122.11: 绑定单个IPv4地址
# "[aaaa::a8aa:ff:fe09:57d8]": 绑定单个IPv6地址
bind-address: "*"

# 规则模式：rule（规则） / global（全局代理）/ direct（全局直连）/ script (脚本)
mode: rule

# 设置日志输出级别 (默认级别：silent,即不输出任何内容,以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / info / warning / error / debug。级别越高日志输出量越大,越倾向于调试,若需要请自行开启。
log-level: info

# Clash 的 RESTful API, 127.0.0.1:9090 | 0.0.0.0:9090
external-controller: 127.0.0.1:9090

# RESTful API 的口令 (可选)
# 通过指定 HTTP 头 `Authorization: Bearer ${secret}` 进行身份验证
# 如果RESTful API在 0.0.0.0 上监听, 务必设置一个 secret 密钥
secret: ""

# 配置目录的相对路径或静态 Web 资源目录的绝对路径. Clash core 将在
# `http://{{external-controller}}/ui` 中提供服务.
# http://0.0.0.0:9090/ui
# external-ui: folder
external-ui: ./

# 本地 SOCKS5 / HTTP(S) 服务认证
# authentication:
#   - user1:pass1
#   - user2:pass2
authentication: []

# ipv6开关,当设置为 false 时, 解析器不会将主机名解析为 IPv6 地址
ipv6: false

# 用于DNS服务器和连接建立的静态主机 (如/etc/hosts) .
#
# 支持通配符主机名 (例如 *.clash.dev, *.foo.*.example.com)
# 非通配符域名优先级高于通配符域名
# 例如 foo.example.com > *.example.com > .example.com
# P.S. +.foo.com 等于 .foo.com 和 foo.com
hosts:
    "*.clash.dev": 127.0.0.1
    ".dev": 127.0.0.1
    "alpha.clash.dev": "::1"

dns:
    enable: false # dns开关
    ipv6: true    # 当为 false 时, AAAA 查询的响应将为空
    listen: 0.0.0.0:53  # dns监听服务
    enhanced-mode: fake-ip # dns处理模式, redir-host模式自premium-2023.02.16开始已弃用
    use-hosts: true # 查找 hosts 并返回 IP 记录
    fake-ip-range: 198.18.0.1/16 # Fake IP 地址池 CIDR
    fake-ip-filter:
        # 此列表中的主机名将不会使用fake-ip解析,仍然遵循redir-host处理逻辑
        - +.stun.*.*
        - +.stun.*.*.*
        - +.stun.*.*.*.*
        - +.stun.*.*.*.*.*
        - "*.n.n.srv.nintendo.net"
        - +.stun.playstation.net
        - xbox.*.*.microsoft.com
        - "*.*.xboxlive.com"
        - "*.msftncsi.com"
        - "*.msftconnecttest.com"
        - WORKGROUP
    nameserver-policy:
        # 指定域名查询的解析服务器
        www.baidu.com: 223.6.6.6
        '+.internal.crop.com': 10.0.0.1
    default-nameserver:
        # 为nameserver设置默认值(可选), 必须为 ip
        - 223.6.6.6 # 阿里DNS
        - 223.5.5.5 # 阿里DNS
    nameserver:
        # 默认dns解析 支持 UDP、TCP、DoT、DoH
        - 180.76.76.76 # 百度DNS
        - 119.29.29.29 # 腾讯DNS
        - 117.50.10.10 # ONE DNS纯净版
        - 114.114.114.114 # 114DNS
        - 114.114.115.115 # 114DNS
        - tls://dns.alidns.com:853 # 阿里 DoT DNS
        - https://dns.alidns.com/dns-query # 阿里 DoH DNS
        - https://alidns_ip/dns-query # 阿里 DoH DNS
        - https://doh.360.cn/dns-query # 360 DoH DNS

tun:
    enable: false # tun模式开关
    stack: gvisor #tun模式堆栈, gvisor | system (需系统防火墙放行)
    auto-route: true #自动设置全局路由
    auto-detect-interface: true #自动选择流量出站接口 (与interface-name冲突)
    dns-hijack: #dns劫持,一般设置为 any:53 即可, 即劫持所有 53 端口的 udp 流量
        - any:53
        # - tcp://any:53

# 出站接口名称 (与auto-detect-interface冲突)
interface-name: ""

# 关于clash.DNS的解释
# https://github.com/Fndroid/clash_for_windows_pkg/wiki/DNS%E6%B1%A1%E6%9F%93%E5%AF%B9Clash%EF%BC%88for-Windows%EF%BC%89%E7%9A%84%E5%BD%B1%E5%93%8D
#
# 为什么不在clash.DNS中添加fallback
# https://github.com/Dreamacro/clash/issues/642#issuecomment-816448986
#
# clash.DNS使用fake-ip模式时, 出现系统检测到网卡无法联网, 微软系APP无法登陆使用等问题
# https://docs.cfw.lbyczf.com/contents/tap.html#%E5%AE%89%E8%A3%85-tap-%E7%BD%91%E5%8D%A1
#
# 代理环境中的 DNS 解析行为
# https://blog.skk.moe/post/what-happend-to-dns-in-proxy

# 代理组示例
proxies:
    - { name: Debug, type: socks5, server: 127.0.0.1, port: 1080 }
proxy-groups:
    - name: Proxy
      type: select
      proxies:
          - DIRECT
          - Debug
rules:
    - MATCH,Proxy
